### ISSUE TITLE
Potential to make this plugin more universal

### ISSUE THREAD

**Issue by mgmeyers** [kepano/obsidian-advanced-appearance#8]
Hey @kepano! Finally had a chance to look at this. Great work. 

I have a thought I'd like to run by you. From what I can tell, there are two major things this plugin and other theme specific plugins do:

1. Toggle CSS classes on the `body` element
2. Adjust CSS variables

What if this plugin parsed the theme CSS looking for something like a JSON/YAML frontmatter comment, and constructed the available theme settings accordingly? Something like:

```css
/*
[
	{
		"type": "section",
		"title": "Accent Color",
	},
	{
		"type": "variable-range",
		"title": "Accent color hue",
		"description: "For links and interactive elements",
		"limits": [0, 360, 1],
		"default": 211,
		"variable": "accent-hue"
	},
	{
		"type": "class-toggle",
		"title": "Accented Cursor",
		"description": "The editor cursor takes on your accent color",
		"default": false,
		"className": "fancy-cursor"
	},
	...
]
*/

...CSS goes here...
```

This would allow theme authors a ton of flexibility without requiring users to manage plugins for each theme. What do you think?

**Comment by kepano** [comment]
Interesting idea. I'd like to get feedback from @lishid on this. I think this approach could introduce some potential vulnerabilities and might be better handled in the Obsidian core. I agree that a JSON/YAML format could work but should probably be a separate file, e.g. `themename.json` that plugins can access so that we're not shoehorning it into the CSS file.
